import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const explorerRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const agentRoot = path.resolve(explorerRoot, '..', 'workspaceMonitorAgent');

test('Workspace Monitor is an admin-only Explorer application plugin', () => {
    const explorerManifest = JSON.parse(fs.readFileSync(path.join(explorerRoot, 'manifest.json'), 'utf8'));
    const plugin = JSON.parse(fs.readFileSync(path.join(agentRoot, 'IDE-plugins', 'workspace-monitor', 'config.json'), 'utf8'));
    assert.ok(explorerManifest.enable.includes('workspaceMonitorAgent no-wait'));
    assert.equal(explorerManifest.applicationPlugins['workspace-monitor'], true);
    assert.equal(plugin.pluginCategory, 'application');
    assert.equal(plugin.adminOnly, true);
    assert.equal(plugin.dependencies[0].type, 'embedded');
    assert.deepEqual(plugin.location, ['file-exp:account-menu']);
});

test('Workspace Monitor keeps read-only concerns in separate tabs', () => {
    const base = path.join(agentRoot, 'IDE-plugins', 'workspace-monitor', 'components', 'workspace-monitor-dashboard');
    const html = fs.readFileSync(path.join(base, 'workspace-monitor-dashboard.html'), 'utf8');
    const dashboardScript = fs.readFileSync(path.join(base, 'workspace-monitor-dashboard.js'), 'utf8');
    const moduleNames = ['workspace-monitor-api.js', 'workspace-monitor-charts.js', 'workspace-monitor-resources.js'];
    const moduleScripts = moduleNames.map((name) => fs.readFileSync(path.join(base, name), 'utf8'));
    const script = [dashboardScript, ...moduleScripts].join('\n');
    const css = fs.readFileSync(path.join(base, 'workspace-monitor-dashboard.css'), 'utf8');
    const buttonScript = fs.readFileSync(path.join(agentRoot, 'IDE-plugins', 'workspace-monitor', 'workspace-monitor-button.js'), 'utf8');
    const buttonHtml = fs.readFileSync(path.join(agentRoot, 'IDE-plugins', 'workspace-monitor', 'workspace-monitor-button.html'), 'utf8');
    for (const label of ['Overview', 'Resources', 'Router Logs', 'Policy Audit', 'DPU Audit']) {
        assert.match(html, new RegExp(`>${label}<`));
    }
    for (const sharedClass of ['panel', 'workspace-monitor-tabs', 'workspace-monitor-tab-shell', 'workspace-monitor-tab', 'status visible']) {
        assert.match(html, new RegExp(`class="[^"]*${sharedClass}`));
    }
    assert.doesNotMatch(html, /settings-tabs|settings-tab|application-tabs|application-tab/);
    assert.match(css, /\.workspace-monitor-tab-shell:has\(\.workspace-monitor-tab\[aria-selected="true"\]\)/);
    assert.match(css, /border-radius:\s*10px 10px 0 0/);
    assert.match(html, /<header>\s*<h1>Workspace monitor<\/h1>/);
    assert.match(html, /data-panel="overview"[\s\S]*class="cpu-monitor"[\s\S]*data-panel="resources"/);
    assert.match(html, /class="general-button secondary"/);
    assert.match(script, /className='panel metric-card'/);
    assert.doesNotMatch(`${html}\n${css}`, /workspace-monitor-header|modal-header|modal-title|modal-subtitle/);
    assert.match(script, /\/status\/data\?follow=1/);
    assert.match(script, /if \(tab === 'overview'\) this\.startOverview\(\)/);
    assert.match(script, /setAttribute\('aria-selected', String\(active\)\)/);
    assert.match(script, /createElementNS\(SVG_NAMESPACE, 'svg'\)/);
    assert.match(html, /Total CPU:[\s\S]*Agents CPU:[\s\S]*Router CPU:/);
    assert.match(html, /Total memory:[\s\S]*Agents memory:[\s\S]*Router memory:/);
    assert.match(script, /const agents = runtimes\.reduce/);
    assert.match(script, /const totalCpu = Number\.isFinite\(reportedTotalCpu\)/);
    assert.match(script, /const totalMemory = Number\.isFinite\(reportedTotalMemory\)/);
    assert.match(script, /\{ name: 'total', samples: this\.samples\.map/);
    assert.match(script, /\{ name: 'agents', samples: this\.samples\.map/);
    assert.match(script, /\{ name: 'router', samples: this\.samples\.map/);
    assert.match(script, /for \(const item of series\) appendChartSeries\(svg, item\.samples, scale, item\.name\)/);
    assert.match(html, /data-role="selected-runtime-chart"/);
    assert.match(html, /data-role="selected-runtime-name"/);
    assert.match(html, /data-role="runtime-history-from"/);
    assert.match(html, /data-role="runtime-history-to"/);
    assert.match(html, /data-role="selected-runtime-cpu-history-chart"/);
    assert.match(html, /data-role="selected-runtime-memory-history-chart"/);
    assert.match(html, /class="cpu-monitor resource-item-monitor"[\s\S]*class="history-panel"[\s\S]*class="table-wrap"/);
    assert.match(script, /this\.runtimeSamples = new Map\(\)/);
    assert.match(script, /function runtimeSeriesId/);
    assert.match(script, /this\.selectedKey = this\.entries\[0\]\?\.key \|\| null/);
    assert.match(script, /renderRows\(\) \{/);
    assert.match(script, /renderSelected\(\)/);
    assert.match(script, /selector\.addEventListener\('click'/);
    assert.match(script, /row\.addEventListener\('click', \(\) => this\.select\(entry\.key\)\)/);
    assert.match(script, /renderLiveCpuChart\(chart, \[\{ name: 'agents', samples: cpuSamples \}\]/);
    assert.match(script, /loadSelectedRuntimeHistory\(\)/);
    assert.match(script, /if \(tab === 'resources'\) \{/);
    assert.match(script, /series: \[cpuKey, memoryKey\]/);
    assert.match(script, /renderSelectedRuntimeHistory\(entry, history, cpuKey, memoryKey\)/);
    assert.match(script, /showThreshold: false/);
    assert.match(script, /if \(showThreshold\) appendRecordedThreshold/);
    assert.match(css, /\.resource-runtime-selector\s*\{/);
    assert.match(css, /\.resource-item-monitor \+ \.history-panel\s*\{/);
    assert.match(css, /tr\.selected\s*\{/);
    assert.match(script, /function appendChartTimeline/);
    assert.match(script, /HISTORY_PIXELS_PER_MINUTE = 8/);
    assert.match(script, /MAX_HISTORY_POINTS = 50_000/);
    assert.match(script, /chart-timeline-scrollable/);
    assert.match(script, /host\.scrollLeft = Math\.max/);
    assert.match(script, /function appendTimeAxis/);
    assert.match(script, /class', 'chart-time-axis'/);
    assert.match(script, /width \/ 2/);
    assert.match(script, /function appendHistoryPoints/);
    assert.match(script, /function appendHistorySeries/);
    assert.match(script, /buildHistorySmoothPath/);
    assert.match(script, /function aboveThresholdSegments/);
    assert.match(script, /function thresholdAt/);
    assert.match(script, /valueThresholds/);
    assert.match(script, /item\.valueThresholds\.length \? item\.valueThresholds : item\.thresholds/);
    assert.match(script, /threshold \$\{formattedThreshold\}/);
    assert.match(script, /function appendRecordedThreshold/);
    assert.match(script, /history-threshold-label/);
    assert.match(script, /function appendHistoryYAxis/);
    assert.match(css, /\.history-y-axis\s*\{/);
    assert.match(script, /history-spike/);
    assert.match(script, /point\.addEventListener\('click', select\)/);
    assert.match(script, /dateStyle: 'medium', timeStyle: 'medium'/);
    assert.match(script, /this\.samples\[0\]\.timestamp/);
    assert.match(script, /appendChartTimeline\(host, from, to, \{ contentWidth: chartWidth \}\)/);
    assert.match(css, /\.chart-timeline\s*\{/);
    assert.match(css, /\.chart-timeline-scrollable\s*\{/);
    assert.match(css, /overflow-x:\s*auto/);
    assert.match(css, /\.chart-time-axis,/);
    assert.match(css, /\.history-point\s*\{/);
    assert.match(css, /\.history-area\.history-workspace\s*\{/);
    assert.match(css, /\.history-spike\s*\{/);
    assert.match(css, /\.chart-point-details\s*\{/);
    assert.match(script, / C \$\{controlX\}/);
    assert.doesNotMatch(script, /createElement\('i'\)/);
    assert.match(css, /\.chart-line\s*\{[^}]*stroke:\s*currentColor/s);
    assert.match(css, /\.chart-line-total\s*\{[^}]*var\(--text\)/s);
    assert.match(css, /\.chart-line-agents\s*\{[^}]*var\(--accent\)/s);
    assert.match(css, /\.chart-line-router\s*\{[^}]*var\(--red\)/s);
    assert.match(script, /\/dashboard\/tail\?source=/);
    assert.match(script, /dpu_audit_list/);
    assert.match(script, /dpu_audit_get/);
    assert.match(script, /workspace_monitor_settings_get/);
    assert.match(script, /workspace_monitor_settings_update/);
    assert.match(script, /workspace_monitor_history_query/);
    assert.match(script, /MONITOR_RETRY_DELAYS_MS = \[300, 900, 1_800\]/);
    assert.match(script, /browser_csrf_invalid\|edge_generation_changed/);
    assert.match(script, /resetClient\?\.\('workspaceMonitorAgent'\)/);
    assert.doesNotMatch(html, /data-history-range=/);
    assert.match(html, /data-role="history-from"/);
    assert.match(html, /data-role="history-to"/);
    assert.doesNotMatch(html, /data-local-action="applyHistoryWindow"/);
    assert.match(script, /input\.addEventListener\('change'/);
    assert.match(script, /input\.addEventListener\('focus', refreshMaximum\)/);
    assert.match(script, /input\.addEventListener\('pointerdown', refreshMaximum\)/);
    assert.match(script, /input\.blur\(\)/);
    assert.match(script, /handleHistoryWindowChange\(\)/);
    assert.match(script, /updateHistoryInputLimits\(now = new Date\(\)\)/);
    assert.match(script, /input\.max = maximum/);
    assert.match(script, /clampHistoryInputToPresent\(input, now = new Date\(\)\)/);
    assert.match(script, /input\.value = localDateTimeValue\(now\)/);
    assert.match(script, /from > now \|\| to > now/);
    assert.match(script, /DEFAULT_HISTORY_DURATION_MS = 24 \* 60 \* 60 \* 1000/);
    assert.match(script, /initializeHistoryWindow\(\)/);
    assert.match(script, /timestamp - previous\.timestamp > stepMs \* 1\.5/);
    assert.match(script, /MAX_LOG_CHARS/);
    assert.match(script, /appendData\(chunk\)/);
    assert.match(script, /deleteData\(0,/);
    assert.doesNotMatch(script, /output\.textContent\s*\+/);
    assert.match(script, /MAX_AUDIT_BYTES/);
    assert.match(script, /maxBytes:MAX_AUDIT_BYTES/);
    assert.match(dashboardScript, /import \{ WorkspaceMonitorResources \} from '\.\/workspace-monitor-resources\.js'/);
    assert.match(dashboardScript, /this\.resources = new WorkspaceMonitorResources/);
    assert.doesNotMatch(dashboardScript, /renderResources\(payload\)|renderResourceRows\(entries\)|function appendChartSeries/);
    assert.match(buttonScript, /open\(targetUrl\.toString\(\), '_blank'/);
    assert.match(buttonScript, /this\.hostContext\?\.pluginIcon/);
    assert.match(buttonScript, /getAttribute\('data-plugin-icon'\)/);
    assert.doesNotMatch(buttonHtml, /src="\.\/icon\.svg"/);
    assert.doesNotMatch(`${script}\n${buttonScript}`, /showModal|closeModal/);
    assert.doesNotMatch(css, /dialog\.modal|(^|})\s*(table|pre|footer|th|td)\s*\{/m);
    assert.doesNotMatch(css, /#[0-9a-f]{3,8}\b/i);
    for (const variable of ['--bg', '--text', '--text-soft', '--accent', '--border']) {
        assert.match(css, new RegExp(`var\\(${variable}\\)`));
    }
    assert.doesNotMatch(`${html}\n${script}`, /dashboard\/run|restart|execute command/i);
});

test('Explorer rejects direct admin-only component routes for non-admin users', () => {
    const mainSource = fs.readFileSync(path.join(explorerRoot, 'main.js'), 'utf8');
    assert.match(mainSource, /getRuntimeComponentPolicy\(context\.plugins, pageName\)/);
    assert.match(mainSource, /routePolicy\?\.adminOnly && !isAdminUser\(context\.authenticatedUser\)/);
    assert.match(mainSource, /componentPolicy\?\.adminOnly && !isAdminUser\(context\.authenticatedUser\)/);
    assert.match(mainSource, /error\.code = 'ADMIN_REQUIRED'/);
});
